name: 'dotfiles devenv command Action'
description: 'Wrapper for devenv command execution on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  prefix:
    description: 'The container image to use'
    required: true
    default: ''
  command:
    description: 'Command to execute (sys, start, shell, etc.)'
    required: true
    default: 'shell'
  args:
    description: 'Additional arguments for the command'
    required: false
    default: ''
outputs:
  prefix:
    description: 'The prefix (container image) that was used'
    value: ${{ inputs.prefix }}
runs:
  using: 'composite'
  steps:
    - name: Execute devenv command
      shell: zsh -l
      run: |
        if functions devenv > /dev/null; then
          devenv ${{ inputs.prefix }} ${{ inputs.command }} ${{ inputs.args }}
        else
          echo "Error: devenv function is not defined. Please make sure to run install first"
          exit 1
        fi